# Generated by Django 5.1.4 on 2024-12-17 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Country code must start with "+" and contain up to 3 digits.', regex='^\\+\\d{1,3}$')])),
                ('mobile_number', models.CharField(max_length=15)),
                ('flag_attending', models.CharField(choices=[('yes', 'Yes, I will attend the event'), ('no', "Sorry, I can't attend the event")], max_length=50)),
                ('number_of_people', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('identification_proof', models.CharField(choices=[('adhar_card', 'Adhar Card'), ('passport', 'Passport'), ('driving_license', 'Driving License')], max_length=50)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.eventregistration')),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_transport', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('self', 'Self')], max_length=10)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('departure_date', models.DateField()),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('terminal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('train_number', models.CharField(blank=True, max_length=50, null=True)),
                ('train_arrival_station', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bus_stop', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='dashboard.eventregistration')),
            ],
        ),
    ]
