# Generated by Django 5.1.4 on 2024-12-17 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('event_name', models.CharField(max_length=100)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.events'),
        ),
    ]
