# Generated by Django 5.1.4 on 2024-12-18 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_events_eventregistration_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transportdetails',
            options={'verbose_name_plural': 'Transport Details'},
        ),
        migrations.RenameField(
            model_name='eventregistration',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='transportdetails',
            old_name='arrival_time',
            new_name='arrival_datetime',
        ),
        migrations.RenameField(
            model_name='transportdetails',
            old_name='departure_time',
            new_name='departure_datetime',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='flag_attending',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='bus_stop',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='terminal_name',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='train_arrival_station',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='train_number',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='arrival_details',
            field=models.CharField(default='ff', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='arrival_mode',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('self', 'Self')], default='ok', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='departure_details',
            field=models.CharField(default='ok', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='departure_mode',
            field=models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('self', 'Self')], default='ok', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.events'),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='dashboard.eventregistration'),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('id_proof', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('passport', 'Passport'), ('license', 'Driving License')], max_length=50)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='dashboard.eventregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
