# Generated by Django 5.1.4 on 2024-12-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_eventregistration_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetails',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='transportdetails',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival Date/Time'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='identification_proof',
            field=models.CharField(choices=[('aadhar', 'Aadhar Card'), ('passport', 'Passport'), ('license', 'Driving License')], default='aadhar', max_length=50, verbose_name='Identification Proof'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='dashboard.eventregistration'),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure Date/Time'),
        ),
    ]
