# Generated by Django 5.1.4 on 2024-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_transportdetails_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='arrival_transport',
            field=models.CharField(blank=True, choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('self', 'Self')], max_length=50, null=True, verbose_name='Arrival Transport'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='departure_transport',
            field=models.CharField(blank=True, choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('self', 'Self')], max_length=50, null=True, verbose_name='Departure Transport'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='Email Address'),
        ),
    ]
