# Generated by Django 5.1.4 on 2024-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_eventregistration_arrival_transport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255, verbose_name='Email Address')),
                ('password', models.CharField(default='', max_length=255, verbose_name='Password')),
            ],
        ),
    ]
